/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pubnet/service/netinfo/{service_name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_name: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    service_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceNetinfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pubnet/service/netinfo/ip/{service_ip}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_ip: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    service_ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceNetinfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Error code */
            code?: number;
            /** @description Error name */
            status?: string;
            /** @description Error message */
            message?: string;
            /** @description Errors */
            errors?: {
                [key: string]: unknown;
            };
        };
        PaginationMetadata: {
            total?: number;
            total_pages?: number;
            first_page?: number;
            last_page?: number;
            page?: number;
            previous_page?: number;
            next_page?: number;
        };
        ServiceIp: {
            Address?: string | null;
            Address_v6?: string | null;
            IpType?: string | null;
        };
        Instance: {
            cluster_id?: string | null;
            instance_number?: number | null;
            instance_ip?: string | null;
            instance_ip_v6?: string | null;
        };
        ServiceNetinfo: {
            system_job_id?: string | null;
            applicationID?: string | null;
            app_ns?: string | null;
            app_name?: string | null;
            service_ns?: string | null;
            service_name?: string | null;
            service_job_id?: string | null;
            service_ip_list?: components["schemas"]["ServiceIp"][];
            instance_list?: components["schemas"]["Instance"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
