services:
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:26.2.5-0
    command: ["start-dev", "--import-realm", "--verbose"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: keycloak
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
    volumes:
      - type: bind
        source: "./keycloak/oakestra-gaming.json"
        target: "/opt/keycloak/data/import/oakestra-gaming.json"
        read_only: true
        bind:
          create_host_path: false
          selinux: "Z"
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:9000:9000"
